{
    'name': 'BI Connector — Power BI & Analytics',
    'version': '19.0.1.0.0',
    'category': 'Technical',
    'summary': 'Connect Odoo to Power BI, Tableau & any BI tool via secure OData/REST API with JWT auth',
    'author': 'leapai.ai',
    'website': 'https://leapai.ai',
    'support': 'abdzoro89@gmail.com',
    'maintainer': 'a.osman@bab.com.sa',
    'depends': ['base', 'mail', 'web'],
    'data': [
        'security/bi_security.xml',
        'security/ir.model.access.csv',
        'data/bi_data.xml',
        'views/bi_config_views.xml',
        'views/bi_endpoint_views.xml',
        'views/bi_token_views.xml',
        'views/bi_log_views.xml',
        'views/bi_menu.xml',
    ],
    'images': [
        'static/description/banner.png',
        'static/description/screenshots/06_powerbi_dashboard.jpg',
        'static/description/screenshots/03_endpoints.jpg',
        'static/description/screenshots/02_jwt_tokens.jpg',
        'static/description/screenshots/05_access_logs.jpg',
        'static/description/screenshots/01_config_hub.jpg',
        'static/description/screenshots/04_odata_feed.jpg',
    ],
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}
